sonar.projectKey=crd10lop_-payment-transaction-analytics-dashboard
sonar.organization=cristian-diez
sonar.projectName=Payment Transaction Analytics Dashboard
sonar.sources=.
sonar.exclusions=e2e/**, lib/utils/__tests__/**, *.config.ts, .next/**, coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
